version: '3.8'

services:
  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter_iceberg
    environment:
      - PYSPARK_SUBMIT_ARGS=--packages org.apache.iceberg:iceberg-spark-runtime-3.4_2.12:1.3.0 pyspark-shell
    volumes:
      - F:\projetos\spark_iceberg\data:/home/jovyan/work
    ports:
      - "8888:8888"
